# --- Identidad de la app ---
spring.application.name=universidad

# --- Base de datos H2 ---
spring.datasource.url=jdbc:h2:mem:universidaddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# --- Consola web de H2 (para inspeccionar tablas) ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- Logging SQL (opcional, útil para debug) ---
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
